"""Reverb platform connector.

Auth model: **Personal Access Token** (Reverb-specific OAuth variant).

Generated by the user at Settings → API & Integrations on reverb.com. Scoped
to the operations we need (read_listings, write_listings, read_orders,
read_profile, public). Tokens don't expire as long as the account is active.

Authentication header: ``Authorization: Bearer <token>``

API endpoints we use (or will use):

  GET    /api/my/account              - validate token, returns shop info
  GET    /api/my/listings?sku={sku}   - find a listing by SKU (for updates)
  POST   /api/listings                - create a new listing
  PUT    /api/listings/{id}           - update an existing listing
  GET    /api/categories/flat         - category UUID lookup (cached)
  GET    /api/listing_conditions      - condition UUID lookup (cached)
  GET    /api/my/orders               - list recent orders (for polling)

Reverb API quirks:

  * Every request MUST include ``Accept-Version: 3.0`` header. Without it,
    you get the wrong API shape or outright errors. This is unusual - most
    APIs version via URL path.
  * Content-Type for POST/PUT is ``application/hal+json`` (not regular JSON).
    Reverb uses HAL hypermedia format. We don't traverse _links but we do
    need to set the Content-Type correctly.
  * Listings require category and condition UUIDs from lookup endpoints,
    not human-readable strings. We'll cache these mappings (not yet
    implemented).
  * Photos are uploaded separately after listing creation, not embedded in
    the creation request.
  * Rate limit: not officially documented but conservative is best.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

import httpx

from listing_studio import __version__
from listing_studio.core.credentials import (
    is_connected as _has_creds,
    load_credentials,
)
from listing_studio.core.models import Platform, Template
from listing_studio.platforms.base import PlatformConnector, PostOutcome, PostingError

logger = logging.getLogger(__name__)


class ReverbConnector(PlatformConnector):
    """Reverb API connector (personal access token auth)."""

    platform = Platform.REVERB

    BASE_URL = "https://api.reverb.com/api"
    USER_AGENT = f"ListingStudio/{__version__}"
    TIMEOUT_SECONDS = 30.0

    # ------------------------------------------------------------------
    # Connection helpers
    # ------------------------------------------------------------------

    async def is_connected(self) -> bool:
        return _has_creds(self.platform)

    def _get_token(self) -> str | None:
        creds = load_credentials(self.platform)
        if creds is None:
            return None
        return creds.get("api_key")

    def _headers(self, token: str) -> dict[str, str]:
        """Standard Reverb headers.

        ``Accept-Version: 3.0`` is non-negotiable - without it the API returns
        v2 shapes or rejects the request.
        """
        return {
            "Authorization": f"Bearer {token}",
            "Accept": "application/hal+json",
            "Accept-Version": "3.0",
            "User-Agent": self.USER_AGENT,
        }

    # ------------------------------------------------------------------
    # Test connection
    # ------------------------------------------------------------------

    async def test_connection(self) -> tuple[bool, str | None]:
        """Validate the token by calling /my/account.

        Returns (True, shop_name) on success, (False, error_message) on
        failure. /my/account requires read_profile scope which we always
        request, so any valid token will work here.
        """
        token = self._get_token()
        if not token:
            return False, "Not connected - no token stored"

        try:
            async with httpx.AsyncClient(timeout=self.TIMEOUT_SECONDS) as client:
                response = await client.get(
                    f"{self.BASE_URL}/my/account",
                    headers=self._headers(token),
                )
        except httpx.RequestError as exc:
            return False, f"Network error: {exc}"

        if response.status_code == 401:
            return False, "Invalid token (Reverb rejected the credentials)"
        if response.status_code == 403:
            return False, "Token lacks required permissions (need at least read_profile)"
        if response.status_code != 200:
            return False, f"Reverb error {response.status_code}: {response.text[:200]}"

        try:
            data = response.json()
        except Exception:
            return False, "Reverb returned malformed response"

        # Account response shape varies; try common fields for the display name.
        # The actual shop name lives under "shop" if the user has a seller shop.
        shop = data.get("shop") or {}
        shop_name = (
            shop.get("name")
            or data.get("first_name", "") + " " + data.get("last_name", "")
        ).strip()

        if not shop_name:
            shop_name = data.get("email") or "Reverb account (unnamed)"

        return True, shop_name

    # ------------------------------------------------------------------
    # Posting / listing creation (not yet implemented)
    # ------------------------------------------------------------------

    async def post(self, template: Template, price_cents: int, quantity: int) -> PostOutcome:
        """Create a listing on Reverb.

        Not yet implemented - requires:

        1. Category UUID lookup (via /api/categories/flat) - we need to map
           Dad's product categories to Reverb's taxonomy. Cache the mapping.
        2. Condition UUID lookup - same idea for the condition enum.
        3. Shipping profile selection - Dad has these set up on Reverb already,
           we need to fetch his shipping_profiles list and pick one.
        4. Image hosting strategy - Reverb expects photo URLs, but our photos
           are on Dad's NAS. Options: serve them from our local API while
           the listing is being created, upload via the image endpoint after
           creation (preferred), or use a separate hosting service.

        This is its own multi-hour chunk of work for the next session.
        """
        if not await self.is_connected():
            raise PostingError(
                self.platform,
                "Not connected. Add API token on the Settings screen.",
                is_auth_error=True,
            )

        raise PostingError(
            self.platform,
            "Reverb listing creation isn't implemented yet. We need to wire up "
            "category/condition UUID lookups and the photo upload flow first.",
        )

    # ------------------------------------------------------------------
    # Inventory updates (not yet implemented)
    # ------------------------------------------------------------------

    async def update_inventory(self, external_listing_id: str, new_quantity: int) -> bool:
        """Update the stock count on an existing Reverb listing.

        Reverb supports inventory tracking via PUT /api/listings/{id} with
        "has_inventory" and "inventory" fields. Implementation deferred to
        the same session that builds out the create flow.
        """
        return False

    # ------------------------------------------------------------------
    # Order polling (not yet implemented)
    # ------------------------------------------------------------------

    async def fetch_recent_orders(self, since: datetime) -> list[dict]:
        """Fetch orders modified since the given timestamp.

        Endpoint: GET /api/my/orders/selling/awaiting_shipment (and similar).
        Deferred to next session.
        """
        return []
