"""Reverb platform connector.

Auth: personal access token (Bearer). Generated by the user at
``My Profile → API & Integrations`` on reverb.com.

Listing creation flow (Reverb-specific quirks):

1. **Category and condition are UUIDs**, not strings. We fetch Reverb's
   taxonomy on first use and cache the name→UUID mapping in memory.
2. **Shipping profile is referenced by ID.** We fetch the user's profiles via
   ``/api/my/shipping_profiles`` and pick one (caller can override).
3. **Photos are passed as public URLs in the create payload.** Reverb does
   NOT accept binary photo uploads - there's no working endpoint for that
   (an older multipart attempt at /listings/{id}/images returns 405). The
   caller is responsible for uploading bytes to an image host first
   (see ``core/photo_host.py``) and passing the resulting URLs in via the
   ``photo_urls`` argument to create_draft. Reverb fetches them server-side.
4. **Drafts vs publish.** POST /listings creates a draft by default. To publish,
   the listing has to PUT /listings/{id}/publish later. For our testing today
   we keep everything as drafts so Dad can review before going live.

References:
  https://www.reverb-api.com/docs/create-listings
  https://www.reverb-api.com/docs/personal-token-scopes-1
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

import httpx

from listing_studio import __version__
from listing_studio.core import credentials as creds
from listing_studio.core.models import Platform, Template
from listing_studio.platforms.base import PlatformConnector, PostingError, PostOutcome

logger = logging.getLogger(__name__)


# Map our internal condition strings to Reverb's display names. The actual
# UUIDs are fetched from /api/listing_conditions and matched by display_name.
CONDITION_DISPLAY_MAPPING = {
    "brand_new": "Brand New",
    "new_old_stock": "Mint",       # Reverb has no "NOS" - "Mint" is closest
    "mint": "Mint",
    "excellent": "Excellent",
    "very_good": "Very Good",
    "good": "Good",
    "fair": "Fair",
    "poor": "Poor",
    "b_stock": "B-Stock",
    "non_functioning": "Non Functioning",
}


class ReverbConnector(PlatformConnector):
    """Reverb API connector."""

    platform = Platform.REVERB

    BASE_URL = "https://api.reverb.com/api"
    USER_AGENT = f"ListingStudio/{__version__}"
    TIMEOUT_SECONDS = 30.0

    # Module-level caches (in-memory only - fresh on each app restart, which
    # is fine since taxonomies change rarely)
    _category_uuid_by_name: dict[str, str] | None = None
    _condition_uuid_by_name: dict[str, str] | None = None
    _full_taxonomy: list[dict[str, str]] | None = None

    # ------------------------------------------------------------------
    # Connection helpers
    # ------------------------------------------------------------------

    async def is_connected(self) -> bool:
        return creds.is_connected(self.platform)

    def _get_token(self) -> str | None:
        stored = creds.load_credentials(self.platform)
        if stored is None:
            return None
        return stored.get("api_key")

    def _headers(self, token: str, content_type: str = "application/hal+json") -> dict[str, str]:
        return {
            "Authorization": f"Bearer {token}",
            "Accept": "application/hal+json",
            "Accept-Version": "3.0",
            "Content-Type": content_type,
            "User-Agent": self.USER_AGENT,
        }

    # ------------------------------------------------------------------
    # Test connection
    # ------------------------------------------------------------------

    async def test_connection(self) -> tuple[bool, str | None]:
        token = self._get_token()
        if not token:
            return False, "Not connected - no token stored"

        try:
            async with httpx.AsyncClient(timeout=self.TIMEOUT_SECONDS) as client:
                response = await client.get(
                    f"{self.BASE_URL}/my/account",
                    headers=self._headers(token),
                )
        except httpx.RequestError as exc:
            return False, f"Network error: {exc}"

        if response.status_code == 401:
            return False, "Invalid token"
        if response.status_code == 403:
            return False, "Token lacks required permissions"
        if response.status_code != 200:
            return False, f"Reverb error {response.status_code}"

        try:
            data = response.json()
        except Exception:
            return False, "Reverb returned malformed response"

        shop = data.get("shop") or {}
        shop_name = (
            shop.get("name")
            or (data.get("first_name", "") + " " + data.get("last_name", "")).strip()
            or data.get("email")
            or "Reverb account"
        )
        return True, shop_name

    # ------------------------------------------------------------------
    # Taxonomy lookups (cached)
    # ------------------------------------------------------------------

    async def _ensure_category_mapping(self, client: httpx.AsyncClient, token: str) -> None:
        """Load Reverb's category taxonomy into the in-memory cache.

        Reverb's /api/categories/flat returns ~700 entries. We index them by
        a normalized form of the human name so case/spacing differences don't
        cause misses.
        """
        if ReverbConnector._category_uuid_by_name is not None:
            return

        response = await client.get(
            f"{self.BASE_URL}/categories/flat",
            headers=self._headers(token),
        )
        if response.status_code != 200:
            raise PostingError(
                self.platform,
                f"Couldn't fetch Reverb category taxonomy: {response.status_code}",
            )

        data = response.json()
        # The response is wrapped in {"categories": [...]} or similar
        categories = data.get("categories") if isinstance(data, dict) else data
        if not isinstance(categories, list):
            raise PostingError(self.platform, "Unexpected category response shape")

        mapping: dict[str, str] = {}
        for cat in categories:
            name = cat.get("name") or cat.get("full_name") or ""
            uuid = cat.get("uuid") or cat.get("id")
            if name and uuid:
                # Index by normalized form for fuzzy matching
                mapping[_normalize_name(name)] = uuid
                # Also store full_name path for subcategory lookups
                full = cat.get("full_name")
                if full and full != name:
                    mapping[_normalize_name(full)] = uuid

        ReverbConnector._category_uuid_by_name = mapping
        logger.info("Cached %d Reverb category UUIDs", len(mapping))

    async def search_taxonomy(self, query: str, limit: int = 30) -> list[dict[str, str]]:
        """Search the cached Reverb taxonomy by name.

        Returns a list of {uuid, name, full_name} dicts sorted by relevance:
        exact-match first, then prefix match on the leaf name, then substring
        match anywhere in full_name. Caps at ``limit`` results.

        Loads the taxonomy on first call (cached after). Returns empty list
        if we can't reach Reverb.
        """
        token = self._get_token()
        if not token:
            return []

        try:
            async with httpx.AsyncClient(timeout=self.TIMEOUT_SECONDS) as client:
                await self._ensure_full_taxonomy(client, token)
        except Exception as exc:
            logger.warning("Couldn't load Reverb taxonomy: %s", exc)
            return []

        # _full_taxonomy is the list-of-dicts we cached. Filter by query.
        taxonomy = ReverbConnector._full_taxonomy or []
        if not query:
            # No query: return the first `limit` items
            return taxonomy[:limit]

        q_lower = query.lower().strip()
        if not q_lower:
            return taxonomy[:limit]

        # Score: 100 = exact name match, 50 = name starts with query, 25 = name
        # contains query, 10 = full_name contains query. We sort by descending
        # score then by name length (shorter = more specific).
        scored = []
        for entry in taxonomy:
            name_lower = (entry.get("name") or "").lower()
            full_lower = (entry.get("full_name") or "").lower()
            score = 0
            if name_lower == q_lower:
                score = 100
            elif name_lower.startswith(q_lower):
                score = 50
            elif q_lower in name_lower:
                score = 25
            elif q_lower in full_lower:
                score = 10
            if score > 0:
                scored.append((score, len(name_lower), entry))

        scored.sort(key=lambda t: (-t[0], t[1]))
        return [entry for (_score, _len, entry) in scored[:limit]]

    async def _ensure_full_taxonomy(self, client: httpx.AsyncClient, token: str) -> None:
        """Fetch and cache the full Reverb category list with all metadata.

        This is separate from _ensure_category_mapping (which only stores
        name->uuid for posting) because the search UI needs full_name and
        hierarchy info too.
        """
        if ReverbConnector._full_taxonomy is not None:
            return

        response = await client.get(
            f"{self.BASE_URL}/categories/flat",
            headers=self._headers(token),
        )
        if response.status_code != 200:
            raise RuntimeError(f"Taxonomy fetch failed: {response.status_code}")

        data = response.json()
        categories = data.get("categories") if isinstance(data, dict) else data
        if not isinstance(categories, list):
            raise RuntimeError("Unexpected taxonomy shape")

        entries = []
        for cat in categories:
            uuid = cat.get("uuid") or cat.get("id")
            name = cat.get("name") or ""
            full = cat.get("full_name") or name
            parent_uuid = cat.get("parent_uuid")
            if uuid and name:
                entries.append({
                    "uuid": uuid,
                    "name": name,
                    "full_name": full,
                    "parent_uuid": parent_uuid,
                })

        ReverbConnector._full_taxonomy = entries
        logger.info("Cached %d Reverb taxonomy entries with full metadata", len(entries))

    async def _ensure_condition_mapping(self, client: httpx.AsyncClient, token: str) -> None:
        """Load Reverb's listing conditions into the in-memory cache."""
        if ReverbConnector._condition_uuid_by_name is not None:
            return

        response = await client.get(
            f"{self.BASE_URL}/listing_conditions",
            headers=self._headers(token),
        )
        if response.status_code != 200:
            raise PostingError(
                self.platform,
                f"Couldn't fetch Reverb conditions: {response.status_code}",
            )

        data = response.json()
        conditions = data.get("conditions") if isinstance(data, dict) else data
        if not isinstance(conditions, list):
            raise PostingError(self.platform, "Unexpected conditions response shape")

        mapping: dict[str, str] = {}
        for cond in conditions:
            name = cond.get("display_name") or cond.get("name") or ""
            uuid = cond.get("uuid") or cond.get("id")
            if name and uuid:
                mapping[_normalize_name(name)] = uuid

        ReverbConnector._condition_uuid_by_name = mapping
        logger.info("Cached %d Reverb condition UUIDs", len(mapping))

    # ------------------------------------------------------------------
    # Shipping profile lookup
    # ------------------------------------------------------------------

    async def fetch_shipping_profiles(self) -> list[dict[str, str]]:
        """Return the user's shipping profiles as a list of {id, name} dicts.

        Used by the UI to populate a dropdown.
        """
        token = self._get_token()
        if not token:
            return []

        async with httpx.AsyncClient(timeout=self.TIMEOUT_SECONDS) as client:
            response = await client.get(
                f"{self.BASE_URL}/my/shipping_profiles",
                headers=self._headers(token),
            )

        if response.status_code != 200:
            logger.warning("Couldn't fetch shipping profiles: %s", response.status_code)
            return []

        data = response.json()
        profiles = data.get("shipping_profiles", []) if isinstance(data, dict) else data
        return [
            {"id": str(p.get("id")), "name": p.get("name", "Unnamed")}
            for p in profiles if p.get("id")
        ]

    # ------------------------------------------------------------------
    # Listing creation
    # ------------------------------------------------------------------

    async def create_draft(
        self,
        template: Template,
        listing_tail: str = "",
        shipping_profile_id: str | None = None,
        photo_urls: list[str] | None = None,
    ) -> dict[str, Any]:
        """Create a draft listing on Reverb.

        Returns a dict with at minimum: ``id``, ``state`` (should be 'draft'),
        ``url`` (preview link). Raises PostingError on failure.

        Args:
            template: the Template to create from
            listing_tail: optional boilerplate text to append to the description
                (e.g. Dad's "About Southwest Acoustic Products" paragraph)
            shipping_profile_id: optional ID of a shipping profile to attach.
                If None, Reverb may reject the listing - the user has to have
                profiles set up.
            photo_urls: optional list of publicly-fetchable image URLs. Reverb
                fetches each URL server-side after listing creation. Pass an
                empty list (or None) to create a draft with no photos - Dad
                can then drag photos into the Reverb UI manually.
        """
        token = self._get_token()
        if not token:
            raise PostingError(
                self.platform,
                "Not connected. Add API token in Settings.",
                is_auth_error=True,
            )

        async with httpx.AsyncClient(timeout=self.TIMEOUT_SECONDS) as client:
            # Resolve category and condition UUIDs. Prefer the
            # category-resolved UUIDs (set when a Category is assigned to
            # the template) over the legacy string fields.
            await self._ensure_condition_mapping(client, token)

            pre_resolved_uuid = getattr(template, "_resolved_reverb_uuid", None)
            pre_resolved_subs = getattr(template, "_resolved_reverb_subcategory_uuids", None) or []

            if pre_resolved_uuid:
                category_uuids = [pre_resolved_uuid] + [s for s in pre_resolved_subs if s][:2]
            else:
                # Fall back to the old string-based resolution
                await self._ensure_category_mapping(client, token)
                category_uuids = _resolve_category_uuids(
                    template.reverb_category, template.reverb_subcategories,
                )

            if not category_uuids:
                raise PostingError(
                    self.platform,
                    "No Reverb category set. Assign this template to a category "
                    "(with a Reverb taxonomy mapping) before posting.",
                )

            condition_uuid = _resolve_condition_uuid(template.condition)

            # Compose description: template description + tail boilerplate
            description = template.description or ""
            if listing_tail:
                description = f"{description}\n\n{listing_tail}".strip()

            # Build the create payload. Reverb's required fields:
            # make, model, categories, condition, price, description
            payload: dict[str, Any] = {
                "make": template.brand or "Unknown",
                "model": template.model or template.name,
                "title": template.title,
                "description": description,
                "categories": [{"uuid": uuid} for uuid in category_uuids],
                "condition": {"uuid": condition_uuid},
                "price": {
                    "amount": _cents_to_decimal_str(template.base_price_cents),
                    "currency": "USD",
                },
                "publish": False,  # KEY: stay as draft
                "has_inventory": template.quantity > 1,
                "inventory": template.quantity,
                "offers_enabled": True,
            }

            # Optional fields
            if template.year:
                payload["year"] = template.year
            if template.finish:
                payload["finish"] = template.finish

            # Photo URLs - Reverb fetches each one server-side. We send the
            # raw URL strings; Reverb's docs accept both that and {url: ""}
            # objects but the bare-string form is what their examples show.
            if photo_urls:
                payload["photos"] = list(photo_urls)

            # Shipping: prefer the template's per-listing shipping fields over
            # an explicit profile ID. If neither is set, Reverb falls back to
            # the seller's default profile (if they have one).
            shipping_payload = _build_shipping_payload(template)
            if shipping_payload:
                payload["shipping"] = shipping_payload
            elif shipping_profile_id:
                payload["shipping_profile_id"] = shipping_profile_id

            response = await client.post(
                f"{self.BASE_URL}/listings",
                headers=self._headers(token),
                json=payload,
            )

        if response.status_code == 401:
            raise PostingError(
                self.platform, "Reverb rejected the token", is_auth_error=True,
            )
        if response.status_code == 422:
            # Validation error - very common, surface details
            try:
                err_data = response.json()
                errors = err_data.get("errors") or err_data.get("message") or err_data
                detail = _format_errors(errors)
            except Exception:
                detail = response.text[:300]
            raise PostingError(
                self.platform, f"Reverb validation error: {detail}",
            )
        if response.status_code not in (200, 201):
            raise PostingError(
                self.platform,
                f"Reverb error {response.status_code}: {response.text[:300]}",
            )

        try:
            data = response.json()
        except Exception as exc:
            raise PostingError(
                self.platform, "Reverb returned malformed response",
            ) from exc

        listing = data.get("listing") or data
        return {
            "id": listing.get("id"),
            "state": listing.get("state", "unknown"),
            "url": listing.get("_links", {}).get("web", {}).get("href"),
            "raw": listing,  # Caller may inspect for debugging
        }

    # ------------------------------------------------------------------
    # PlatformConnector abstract methods (called by generic posting code)
    # ------------------------------------------------------------------

    async def post(self, template: Template, price_cents: int, quantity: int) -> PostOutcome:
        """Post a Template to Reverb.

        Wraps create_draft for the generic posting interface. Used by the
        cross-post pipeline that fires multiple connectors at once.
        """
        # The caller may override price/quantity; mutate locally without saving
        # back. Bit ugly but keeps the create_draft signature focused.
        original_price = template.base_price_cents
        original_qty = template.quantity
        try:
            template.base_price_cents = price_cents
            template.quantity = quantity
            result = await self.create_draft(template)
        finally:
            template.base_price_cents = original_price
            template.quantity = original_qty

        return PostOutcome(
            external_listing_id=str(result["id"]),
            external_listing_url=result.get("url") or "",
        )

    async def update_inventory(self, external_listing_id: str, new_quantity: int) -> bool:
        token = self._get_token()
        if not token:
            return False

        try:
            async with httpx.AsyncClient(timeout=self.TIMEOUT_SECONDS) as client:
                response = await client.put(
                    f"{self.BASE_URL}/listings/{external_listing_id}",
                    headers=self._headers(token),
                    json={"has_inventory": True, "inventory": new_quantity},
                )
            return response.status_code in (200, 204)
        except httpx.RequestError as exc:
            logger.warning("Failed to update Reverb inventory: %s", exc)
            return False

    async def fetch_recent_orders(self, since: datetime) -> list[dict]:
        """Polling stub. Not yet implemented."""
        return []


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def _normalize_name(name: str) -> str:
    """Lowercase + strip extra whitespace for fuzzy mapping lookups."""
    return " ".join(name.lower().strip().split())


def _resolve_category_uuids(category: str | None, subcategories: str | None) -> list[str]:
    """Turn human category names into Reverb UUIDs.

    Returns up to 3 UUIDs - one root + up to 2 subcategories - matching
    Reverb's API constraint.
    """
    if not category:
        return []
    mapping = ReverbConnector._category_uuid_by_name or {}
    uuids = []

    main = mapping.get(_normalize_name(category))
    if main:
        uuids.append(main)

    if subcategories:
        for sub in (s.strip() for s in subcategories.split(",")):
            if not sub or len(uuids) >= 3:
                continue
            # Try both the bare name and the "Parent > Sub" form
            sub_uuid = (
                mapping.get(_normalize_name(sub))
                or mapping.get(_normalize_name(f"{category} > {sub}"))
            )
            if sub_uuid and sub_uuid not in uuids:
                uuids.append(sub_uuid)

    return uuids


def _resolve_condition_uuid(template_condition: str) -> str | None:
    """Turn our internal condition string into a Reverb UUID."""
    mapping = ReverbConnector._condition_uuid_by_name or {}
    display = CONDITION_DISPLAY_MAPPING.get(template_condition, "Mint")
    return mapping.get(_normalize_name(display))


def _cents_to_decimal_str(cents: int) -> str:
    return f"{cents / 100:.2f}"


def _build_shipping_payload(template: Any) -> dict | None:
    """Build the ``shipping`` block of a Reverb create-listing payload.

    Reverb format:
        {"rates": [{"region_code": "US_CON", "rate": {"amount": "0.00", "currency": "USD"}}]}

    Region codes:
      US_CON  - US continental (lower 48)
      XX      - Everywhere else (international)

    Returns None if the template has no shipping config (caller should fall
    back to a profile in that case).

    Currently we only set US continental (free or flat). International is
    deferred per Dad's "domestic only" preference; if he ever wants to ship
    international, we add it here.
    """
    ship_type = getattr(template, "reverb_shipping_type", None)
    if not ship_type:
        return None

    if ship_type == "free":
        amount_cents = 0
    elif ship_type == "flat":
        amount_cents = getattr(template, "reverb_shipping_flat_cents", 0) or 0
    else:
        # Unknown type - safer to skip than guess
        return None

    return {
        "rates": [
            {
                "region_code": "US_CON",
                "rate": {
                    "amount": _cents_to_decimal_str(amount_cents),
                    "currency": "USD",
                },
            },
        ],
    }


def _format_errors(errors: Any) -> str:
    """Reverb validation errors come back in varied shapes; flatten to a string."""
    if isinstance(errors, str):
        return errors[:300]
    if isinstance(errors, dict):
        parts = []
        for k, v in errors.items():
            if isinstance(v, list):
                parts.append(f"{k}: {', '.join(str(x) for x in v)}")
            else:
                parts.append(f"{k}: {v}")
        return "; ".join(parts)[:500]
    if isinstance(errors, list):
        return "; ".join(str(e) for e in errors)[:500]
    return str(errors)[:300]
